// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DeepCopy","status":true,"description":"オブジェクトをディープコピーするための関数","parameters":{}},
{"name":"----------------------","status":false,"description":"-----------------------------------------------------------","parameters":{}},
{"name":"planck","status":true,"description":"物理エンジン","parameters":{}},
{"name":"planckMZ","status":true,"description":"planck.js をRPGツクールMZで動作させる","parameters":{"DefaultGravity":"0.0, 3.0","DebugCollideDisplay":"true","DebugGravityDisplay":"false"}},
{"name":"----------------------","status":false,"description":"-----------------------------------------------------------","parameters":{}},
{"name":"GABA_SkipTitle","status":true,"description":"タイトル画面をスキップします。","parameters":{}}
];
